"""
Gmail Watcher for Personal AI Employee System

Monitors Gmail account for new emails and creates action files in /Needs_Action
"""
import os
import time
import json
from datetime import datetime
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
import email
import base64

# Scopes for Gmail API
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

class GmailWatcher:
    def __init__(self, config_file='watcher_config.json'):
        self.config = self.load_config(config_file)
        self.service = self.authenticate()
        self.last_check_time = self.get_last_check_time()

    def load_config(self, config_file):
        """Load configuration from JSON file"""
        try:
            with open(config_file, 'r') as f:
                return json.load(f)
        except FileNotFoundError:
            print(f"Config file {config_file} not found. Using defaults.")
            return {}

    def authenticate(self):
        """Authenticate with Gmail API"""
        creds = None
        # Token file stores the user's access and refresh tokens
        if os.path.exists('token.json'):
            creds = Credentials.from_authorized_user_file('token.json', SCOPES)

        # If there are no valid credentials, request authorization
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(
                    'credentials.json', SCOPES)
                creds = flow.run_local_server(port=0)

            # Save credentials for next run
            with open('token.json', 'w') as token:
                token.write(creds.to_json())

        return build('gmail', 'v1', credentials=creds)

    def get_last_check_time(self):
        """Get timestamp of last check from file or return current time"""
        try:
            with open('.gmail_last_check', 'r') as f:
                return float(f.read().strip())
        except FileNotFoundError:
            return time.time()

    def save_last_check_time(self, timestamp):
        """Save timestamp of last check"""
        with open('.gmail_last_check', 'w') as f:
            f.write(str(timestamp))

    def get_new_emails(self):
        """Get new emails since last check"""
        # Calculate time range
        query = f'after:{int(self.last_check_time)}'

        results = self.service.users().messages().list(
            userId='me', q=query).execute()
        messages = results.get('messages', [])

        new_emails = []
        for msg in messages:
            msg_data = self.service.users().messages().get(
                userId='me', id=msg['id']).execute()

            # Extract email headers and body
            headers = msg_data['payload'].get('headers', [])
            subject = ''
            sender = ''

            for header in headers:
                if header['name'] == 'Subject':
                    subject = header['value']
                elif header['name'] == 'From':
                    sender = header['value']

            # Decode body if present
            body = ''
            payload = msg_data['payload']
            if 'parts' in payload:
                for part in payload['parts']:
                    if part['mimeType'] == 'text/plain':
                        data = part['body']['data']
                        body = base64.urlsafe_b64decode(data.encode('ASCII')).decode('utf-8')
                        break

            new_emails.append({
                'id': msg['id'],
                'subject': subject,
                'sender': sender,
                'body': body[:500],  # Limit body length
                'timestamp': time.time()
            })

        return new_emails

    def create_action_file(self, email_data):
        """Create action file in /Needs_Action directory"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"email_{timestamp}_{email_data['id'][:8]}.md"
        filepath = os.path.join("Needs_Action", filename)

        content = f"""---
type: email
priority: normal
status: pending
sender: "{email_data['sender']}"
subject: "{email_data['subject']}"
---

## Email Content

**From:** {email_data['sender']}
**Subject:** {email_data['subject']}

{email_data['body']}

---
**Automatically generated by Gmail Watcher at {datetime.now().isoformat()}**
"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Created action file: {filepath}")

    def run_once(self):
        """Run one check cycle"""
        print("Checking Gmail for new messages...")
        new_emails = self.get_new_emails()

        for email_data in new_emails:
            self.create_action_file(email_data)

        # Update last check time
        self.save_last_check_time(time.time())
        print(f"Checked {len(new_emails)} new emails")

    def run(self, interval=300):  # Default 5 minutes
        """Run continuously with specified interval"""
        print("Starting Gmail Watcher...")
        while True:
            try:
                self.run_once()
                time.sleep(interval)
            except KeyboardInterrupt:
                print("Gmail Watcher stopped by user")
                break
            except Exception as e:
                print(f"Error in Gmail Watcher: {e}")
                time.sleep(60)  # Wait 1 minute before retrying

if __name__ == "__main__":
    watcher = GmailWatcher()
    watcher.run()